version: '3.5'
services:
    php-fpm:
        build:
            context: ./php-fpm
        restart: always
        expose:
            - 9003
        volumes:
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ${CODE_PATH}:/var/www:cached
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/entrypoint:/docker-entrypoint-initdb.d/
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../www:/var/www
        ports:
            - "80:80"
        restart: always
        depends_on:
            - php-fpm
            - postgres
